Revert "Remove scope operator 'std::' as 'using namespace std;' is set"
This reverts commit e20476d6fba6f30c9787095b052a6d2fb832d24d, which cause
building error on Ununtu 12.04 LTS:

error: call of overloaded ‘isnan(double&)’ is ambiguous